### ISSUE TITLE
получиться.04 первый пример "eventive arg1" мне непонятный, arg1 не существует в предложении?

### ISSUE THREAD

**Issue by hoffmjac** [cu-clear/RussianPropbank#3]
```
</roles>
	  <example name="eventive arg1" src="Эльвира Савкина, «Если нужно, могу выпустить когти», 2002 г. (цитата из Национального корпуса русского языка, см. Список литературы)" type="">
        <text>Зрелищность акции позволила собрать максимальное количество зрителей -- получился праздник городского масштаба , соответственно , параллельно с дегустацией напитка .</text>
		<rel f="">получилось</rel>
		<arg f="" n="1">сделать то, о чём он давно мечтал</arg>
```
Я работаю над этим репоситорием для проекта, и вот это нашел. Исходя из своего опыта с вашими другими rolesets до этого момента, я ожидал запись для аргумента, которая была бы в предложении. 

I am working on this repository for a project and I found this. Based on my experience with your other rolesets until this point, I expected the entry for the argument to be from the sentence itself.

**Comment by skatje-myers** [comment]
Thanks for catching that error! I've updated the example.
